version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - storybook
      parcel:
        patterns:
          - '@parcel/*'
          - parcel
